# Site settings
title: BrainVis
description: BrainVis official project site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: BrainVis
user_authors: <p><a href="https://romgai.github.io/">Honghao Fu</a><sup>1,2</sup>, <a href="https://personal.ntu.edu.sg/zqshen/">Zhiqi Shen</a><sup>2</sup>, Jing Jih Chin<sup>2</sup>, <a href="https://wanghao.tech/">Hao Wang</a><sup>1†</sup><br>&nbsp<br><sup>1</sup>The Hong Kong University of Science and Technology (Guangzhou)<br><sup>2</sup>Nanyang Technological University<br>&nbsp<br><sup>†</sup>Corresponding Author</p>
user_abstract: <p class="left-align">Analyzing and reconstructing visual stimuli from brain signals effectively advances understanding of the human visual system. 
However, the EEG signals are complex and contain a amount of noise. This leads to substantial limitations in existing works of visual stimuli reconstruction from EEG, such as difficulties in aligning EEG embeddings with the fine-grained semantic information and a heavy reliance on additional large self-collected dataset for training. To address these challenges, we propose a novel approach called BrainVis. Firstly, we divide the EEG signals into various units and apply a self-supervised approach on them to obtain EEG time-domain features, in an attempt to ease the training difficulty. Additionally, we also propose to utilize the frequency-domain features to enhance the EEG representations. Then, we simultaneously align EEG time-frequency embeddings with the interpolation of the coarse and fine-grained semantics in the CLIP space, to highlight the primary visual components and reduce the cross-modal alignment difficulty. Finally, we adopt the cascaded diffusion models to reconstruct images. Our proposed BrainVis outperforms state of the arts in both semantic fidelity reconstruction and generation quality. Notably, we reduce the training data scale to 10% of the previous work.</p>
user_Contribution: <p class="left-align"><ul>
  <li>We improve the self-supervised embedding method for EEG time-domain features, eliminating the reliance on additional self-collected large-scale dataset. </li>
  <li>We propose the first EEG visual stimuli reconstruction method that integrates time and frequency-domain features, enhancing the EEG representations.</li>
  <li>BrainVis generates images with higher accuracy and better quality, and also overcomes previous limitation that was limited to only coarse-grained reconstruction.</li>
</ul>
</p>
user_Experiment_Results: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult.
user_BibTeX: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult.
user_Acknowledgments: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult.

user_title: Exploring the bridge between brain and visual signals via image reconstruction
email: hfu006@ntu.edu.sg
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
#linkedin_username: murraco
github_username:  RomGai/BrainVis
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

