# Site settings
title: BrainVis
description: BrainVis official project site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: BrainVis
user_authors: <p>Honghao Fu<sup>1,2</sup>, Zhiqi Shen<sup>2</sup>, Jing Jih Chin<sup>2</sup>, Hao Wang<sup>1</sup> (Corresponding Author)<br><sup>1</sup>The Hong Kong University of Science and Technology (Guangzhou)<br><sup>2</sup>Nanyang Technological University</p>
user_abstract: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult.
user_Contribution: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult.
user_Experiment_Results: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult.
user_BibTeX: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult.
user_Acknowledgments: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult.

user_title: Exploring the bridge between brain and visual signals via image reconstruction
email: hfu006@ntu.edu.sg
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
#linkedin_username: murraco
github_username:  RomGai/BrainVis
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

